version: '3.4'

services:
  zebraiotconnector.backend.api:
    image: ${DOCKER_REGISTRY-}zebraiotconnectorbackendapi
    build:
      context: .
      dockerfile: ./ZebraIoTConnector.Backend.API/Dockerfile
    # Shared Network
    networks:
      - mosquitto_go_net
    # Console output
    # stdin_open: true
    # tty: true
    ports:
      - "5001:80"
      - "5002:443"
    environment:
      - ASPNETCORE_URLS=http://+:80
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=sql.data,1433;Database=ZebraRFID_DockDoor;MultipleActiveResultSets=true;User ID=sa;Password=Zebra2022!
      - Mqtt__BrokerHost=mosquitto
    depends_on:
      sql.data:
        condition: service_started
      mosquitto:
        condition: service_started
  sql.data:
    image: mcr.microsoft.com/mssql/server:2019-latest
    platform: linux/amd64
    environment:
      - SA_PASSWORD=Zebra2022!
      - ACCEPT_EULA=Y
      - MSSQL_PID=Developer
    ports:
      - "1433:1433"
    volumes:
      - sql_data:/var/opt/mssql
    # Shared Network
    networks:
        - mosquitto_go_net
    healthcheck:
      test: ["CMD-SHELL", "/opt/mssql-tools18/bin/sqlcmd -S localhost -U sa -P 'Zebra2022!' -Q 'SELECT 1' -C || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 20
      start_period: 60s  

  mosquitto:
      image: eclipse-mosquitto:latest
      container_name: mosquitto
      restart: always
      volumes:
        - ./mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf:rw
      ports:
        - 1883:1883
        - 9001:9001   
      # Shared Network
      networks:
          - mosquitto_go_net
      # Make mosquitto reachable from outside (FX reader)
      hostname: "$host_name"

networks:
  mosquitto_go_net:
    driver: bridge

volumes:
  sql_data: